name: terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform workflow
    runs-on: ubuntu-latest
    environment: production
    steps:
      # Repository checkout 
      - name: checkout Repos
        run: echo "checkout the repository"
      - name: Checkout code
        uses: actions/checkout@v4
       # setting up terraform 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
        #configuring terraform credentials 
      - name: echo
        run : echo " now configuring aws"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1
      

      - name: Verify Terraform Version
        run: terraform -version
      - name: Setup TFLint uses
        uses: terraform-linterssetup-tflint@v1
        with: 
            tflint_version: v0.52.0
      - name: Init TFLint
        run: tflint --init
      - name: Run TFLint
        run: tflint -f compact
      
         #Initializing terraform 
      - name: Initializing Terraform
        run: terraform init
        working-directory: ./terraform-project  
        #Terraform validate
      - name: Check Terraform Formatting
        run: terraform validate 
        working-directory: ./terraform-project
        #Terraform plan 
      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform-project
        # Output terraform plan in a file 
      - run: terraform plan -out=tfplan
        working-directory: ./terraform-project

      - name: Show Terraform Plan run
        run: terraform show -json tfplan | jq
        working-directory: ./terraform-project
        # Terraform apply  
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform-project
      - run: echo " waiting for 2minutes before destruction"
      - name: single line script
        run: sleep 120 
       # Terraform destroy
      - name: Terraform destroy
        run: terraform destroy -auto-approve
        working-directory: ./terraform-project

      - run: echo " Done destroying the infrastructure"
      - run: echo "pipeline"
      
     