name: terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1

      - name: Verify Terraform Version
        run: terraform -version

      - name: Initializing Terraform
        run: terraform init
        working-directory: ./terraform-project  

      - name: Check Terraform Formatting
        run: terraform validate 
        working-directory: ./terraform-project
        
      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform-project

      # Optional: Automatically Apply Terraform Plan
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform-project


      
     