name: terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform workflow
    runs-on: windows-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4

    
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.7  

      - name: Install Terraform
        shell: pwsh
        run: |
            # Download the Terraform zip file
            Invoke-WebRequest -Uri https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_windows_amd64.zip -OutFile terraform.zip
  
            # Extract the zip file
            Expand-Archive -Path terraform.zip -DestinationPath C:\terraform
  
            # Add Terraform to PATH
            [System.Environment]::SetEnvironmentVariable("PATH", "$env:PATH;C:\terraform", [System.EnvironmentVariableTarget]::Machine)
  
            
  
        # Step 3: Verify Terraform Installation
      - name: Verify Terraform Version
        run: terraform -version
        shell: pwsh

      
      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform-project  

      
      - name: Check Terraform Formatting
        run: terraform fmt -check
        working-directory: ./terraform-project

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform-project

      