name: terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform workflow
    runs-on: ubuntu-latest
    environment: production
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Terraform 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.1.7"

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Verify Terraform Version
      - name: Verify Terraform Version
        run: terraform -version

      # Setup TFLint
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1
        with: 
          tflint_version: v0.52.0

      # Initialize TFLint
      - name: Init TFLint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Run TFLint
      - name: Run TFLint
        run: tflint -f compact

      # Initialize Terraform 
      - name: Initializing Terraform
        run: terraform init
        working-directory: ./terraform-project  

      # Validate Terraform
      - name: Validate Terraform
        run: terraform validate
        working-directory: ./terraform-project

      # Generate Terraform Plan
      - name: Generate Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./terraform-project

      # Verify Plan File
      - name: Verify Plan File
        run: ls -la ./terraform-project/tfplan
        working-directory: ./terraform-project

      # Show Terraform Plan
      - name: Show Terraform Plan
        run: terraform show tfplan
        working-directory: ./terraform-project

      
      
      

      # Apply Terraform changes 
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform-project

      # Wait for 2 minutes before destruction
      - name: Wait for 2 Minutes
        run: sleep 120

      # Destroy Terraform resources
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./terraform-project

      # Cleanup
      - name: Cleanup
        run: echo "Done destroying the infrastructures"
